[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:;"
    
    # MIME type headers
    Content-Type = "text/javascript; charset=utf-8"
    
    # Cache control
    Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
